// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Slice for *BlogPost → Slice zone*
 */
export type BlogpostDocumentDataBodyBlogpostintroSlice = prismic.Slice<
  "blogpostintro",
  Record<string, never>,
  never
>;

type BlogpostDocumentDataBodySlice = BlogpostDocumentDataBodyBlogpostintroSlice;

/**
 * Content for BlogPost documents
 */
interface BlogpostDocumentData {
  /**
   * BlogPostRichText field in *BlogPost*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.blogpostrichtext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blogpostrichtext: prismic.RichTextField;

  /**
   * Slice zone field in *BlogPost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<BlogpostDocumentDataBodySlice>;
}

/**
 * BlogPost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
  >;

type Blogpost2DocumentDataSlicesSlice = HeroSlice;

/**
 * Content for OLD_blogpost2 documents
 */
interface Blogpost2DocumentData {
  /**
   * Slice Zone field in *OLD_blogpost2*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost2.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<Blogpost2DocumentDataSlicesSlice> /**
   * Meta Title field in *OLD_blogpost2*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogpost2.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OLD_blogpost2*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogpost2.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OLD_blogpost2*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost2.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OLD_blogpost2 document from Prismic
 *
 * - **API ID**: `blogpost2`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Blogpost2Document<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<Blogpost2DocumentData>,
    "blogpost2",
    Lang
  >;

type Blogpost2slicesDocumentDataSlicesSlice = TextAndImageSlice | HeroSlice;

/**
 * Content for OLD_BlogPost2Slices documents
 */
interface Blogpost2slicesDocumentData {
  /**
   * Slice Zone field in *OLD_BlogPost2Slices*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost2slices.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<Blogpost2slicesDocumentDataSlicesSlice> /**
   * Meta Title field in *OLD_BlogPost2Slices*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogpost2slices.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OLD_BlogPost2Slices*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogpost2slices.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OLD_BlogPost2Slices*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost2slices.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OLD_BlogPost2Slices document from Prismic
 *
 * - **API ID**: `blogpost2slices`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Blogpost2slicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<Blogpost2slicesDocumentData>,
    "blogpost2slices",
    Lang
  >;

type Blogpost01DocumentDataSlicesSlice =
  | ImageTextHSlice
  | BlogPostPreviewSlice
  | TextImageTextSlice;

/**
 * Content for blogpost_01 documents
 */
interface Blogpost01DocumentData {
  /**
   * blogPostCategory field in *blogpost_01*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost_01.blogpostcategory
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  blogpostcategory: prismic.ContentRelationshipField<"category">;

  /**
   * Slice Zone field in *blogpost_01*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost_01.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<Blogpost01DocumentDataSlicesSlice> /**
   * Meta Title field in *blogpost_01*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogpost_01.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *blogpost_01*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogpost_01.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blogpost_01*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost_01.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * blogpost_01 document from Prismic
 *
 * - **API ID**: `blogpost_01`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Blogpost01Document<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<Blogpost01DocumentData>,
    "blogpost_01",
    Lang
  >;

type BlogposttestDocumentDataSlicesSlice = TextAndImageSlice;

/**
 * Content for OLD_BlogPostTest documents
 */
interface BlogposttestDocumentData {
  /**
   * Slice Zone field in *OLD_BlogPostTest*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposttest.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogposttestDocumentDataSlicesSlice> /**
   * Meta Title field in *OLD_BlogPostTest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogposttest.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *OLD_BlogPostTest*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogposttest.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *OLD_BlogPostTest*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogposttest.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * OLD_BlogPostTest document from Prismic
 *
 * - **API ID**: `blogposttest`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogposttestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogposttestDocumentData>,
    "blogposttest",
    Lang
  >;

/**
 * Item in *category → Subcategories*
 */
export interface CategoryDocumentDataSubcategoriesItem {
  /**
   * Subcategory field in *category → Subcategories*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: category.subcategories[].subcategory
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  subcategory: prismic.ContentRelationshipField<"category">;
}

/**
 * Content for category documents
 */
interface CategoryDocumentData {
  /**
   * Title field in *category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: title
   * - **API ID Path**: category.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: link
   * - **API ID Path**: category.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;

  /**
   * Order field in *category*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 1
   * - **API ID Path**: category.order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;

  /**
   * Subcategories field in *category*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: category.subcategories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  subcategories: prismic.GroupField<
    Simplify<CategoryDocumentDataSubcategoriesItem>
  >;
}

/**
 * category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

interface GlobalmenuDocumentData {}

/**
 * globalMenu document from Prismic
 *
 * - **API ID**: `globalmenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalmenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalmenuDocumentData>,
    "globalmenu",
    Lang
  >;

export type AllDocumentTypes =
  | BlogpostDocument
  | Blogpost2Document
  | Blogpost2slicesDocument
  | Blogpost01Document
  | BlogposttestDocument
  | CategoryDocument
  | GlobalmenuDocument;

/**
 * Primary content in *BlogPostPreview → Default → Primary*
 */
export interface BlogPostPreviewSliceDefaultPrimary {
  /**
   * BlogPostImagePreview field in *BlogPostPreview → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_preview.default.primary.blogpostimagepreview
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  blogpostimagepreview: prismic.ImageField<never>;

  /**
   * BlogPostTitlePreview field in *BlogPostPreview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post_preview.default.primary.blogposttitlepreview
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blogposttitlepreview: prismic.KeyTextField;

  /**
   * BlogPostDescPreview field in *BlogPostPreview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: BlogPostDescPreview
   * - **API ID Path**: blog_post_preview.default.primary.blogpostdescpreview
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blogpostdescpreview: prismic.RichTextField;
}

/**
 * Default variation for BlogPostPreview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostPreviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostPreviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPostPreview*
 */
type BlogPostPreviewSliceVariation = BlogPostPreviewSliceDefault;

/**
 * BlogPostPreview Shared Slice
 *
 * - **API ID**: `blog_post_preview`
 * - **Description**: BlogPostPreview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostPreviewSlice = prismic.SharedSlice<
  "blog_post_preview",
  BlogPostPreviewSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero.default.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * callToActionLabel field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * callToActionLink field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Image Right → Primary*
 */
export interface HeroSliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero.imageRight.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * callToActionLabel field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * callToActionLink field in *Hero → Image Right → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.imageRight.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;
}

/**
 * Image Right variation for Hero Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<HeroSliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceImageRight;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageTextH → Default → Primary*
 */
export interface ImageTextHSliceDefaultPrimary {
  /**
   * Image field in *ImageTextH → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_h.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * text field in *ImageTextH → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem Ipsum dolor si amet
   * - **API ID Path**: image_text_h.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for ImageTextH Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextHSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTextHSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageTextH*
 */
type ImageTextHSliceVariation = ImageTextHSliceDefault;

/**
 * ImageTextH Shared Slice
 *
 * - **API ID**: `image_text_h`
 * - **Description**: ImageTextH
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageTextHSlice = prismic.SharedSlice<
  "image_text_h",
  ImageTextHSliceVariation
>;

/**
 * Primary content in *TextAndImage → Default → Primary*
 */
export interface TextAndImageSliceDefaultPrimary {
  /**
   * Text field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Image field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TextAndImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextAndImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextAndImage*
 */
type TextAndImageSliceVariation = TextAndImageSliceDefault;

/**
 * TextAndImage Shared Slice
 *
 * - **API ID**: `text_and_image`
 * - **Description**: TextAndImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndImageSlice = prismic.SharedSlice<
  "text_and_image",
  TextAndImageSliceVariation
>;

/**
 * Primary content in *TextImageText → Default → Primary*
 */
export interface TextImageTextSliceDefaultPrimary {
  /**
   * FirstRichText field in *TextImageText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: FirstRichText
   * - **API ID Path**: text_image_text.default.primary.firstrichtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  firstrichtext: prismic.RichTextField;

  /**
   * Image field in *TextImageText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_image_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * FirstRichText2 field in *TextImageText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: FirstRichText2
   * - **API ID Path**: text_image_text.default.primary.firstrichtext2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  firstrichtext2: prismic.RichTextField;
}

/**
 * Default variation for TextImageText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextImageTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextImageTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextImageText*
 */
type TextImageTextSliceVariation = TextImageTextSliceDefault;

/**
 * TextImageText Shared Slice
 *
 * - **API ID**: `text_image_text`
 * - **Description**: TextImageText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextImageTextSlice = prismic.SharedSlice<
  "text_image_text",
  TextImageTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogpostDocument,
      BlogpostDocumentData,
      BlogpostDocumentDataBodySlice,
      Blogpost2Document,
      Blogpost2DocumentData,
      Blogpost2DocumentDataSlicesSlice,
      Blogpost2slicesDocument,
      Blogpost2slicesDocumentData,
      Blogpost2slicesDocumentDataSlicesSlice,
      Blogpost01Document,
      Blogpost01DocumentData,
      Blogpost01DocumentDataSlicesSlice,
      BlogposttestDocument,
      BlogposttestDocumentData,
      BlogposttestDocumentDataSlicesSlice,
      CategoryDocument,
      CategoryDocumentData,
      CategoryDocumentDataSubcategoriesItem,
      GlobalmenuDocument,
      GlobalmenuDocumentData,
      AllDocumentTypes,
      BlogPostPreviewSlice,
      BlogPostPreviewSliceDefaultPrimary,
      BlogPostPreviewSliceVariation,
      BlogPostPreviewSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceImageRightPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceImageRight,
      ImageTextHSlice,
      ImageTextHSliceDefaultPrimary,
      ImageTextHSliceVariation,
      ImageTextHSliceDefault,
      TextAndImageSlice,
      TextAndImageSliceDefaultPrimary,
      TextAndImageSliceVariation,
      TextAndImageSliceDefault,
      TextImageTextSlice,
      TextImageTextSliceDefaultPrimary,
      TextImageTextSliceVariation,
      TextImageTextSliceDefault,
    };
  }
}
